apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: html-app
  template:
    metadata:
      labels:
        app: html-app
    spec:
      containers:
      - name: html-app
        image: 654654474502.dkr.ecr.us-east-1.amazonaws.com/html-app:latest
        ports:
        - containerPort: 80